### ISSUE TITLE
无效果

### ISSUE THREAD

**Issue by KanyShigure** [ByteForgeTech/openqq-java#2]
如题，导入了依赖库及github页上的示例代码，无效果
示例代码改动部分：
`String appId = ;
String clientSecret = ;`
这两行改为了直接赋值为机器人的appid和appsecret

                    public void onEvent(GroupAtMessageEvent event) {  
                        System.out.println("1");
                        if (event.getD().getContent().contains("session test")) {
                            event.reply("1");
                        }
                    }

收群@消息代码，理应收到任何消息都打印一条消息出来，但并没有出现

**Comment by mxlt02** [comment]
> 如题，导入了依赖库及github页上的示例代码，无效果 示例代码改动部分： `String appId = ; String clientSecret = ;` 这两行改为了直接赋值为机器人的appid和appsecret
> 
> ```
>                 public void onEvent(GroupAtMessageEvent event) {  
>                     System.out.println("1");
>                     if (event.getD().getContent().contains("session test")) {
>                         event.reply("1");
>                     }
>                 }
> ```
> 
> 收群@消息代码，理应收到任何消息都打印一条消息出来，但并没有出现

log.info("token连接信息: " + botContext.getCertificate().getAccessToken());
麻烦试一下本条代码是否有正常的token输出,

**Comment by KanyShigure** [comment]
> > 如题，导入了依赖库及github页上的示例代码，无效果 示例代码改动部分： `String appId = ; String clientSecret = ;` 这两行改为了直接赋值为机器人的appid和appsecret
> > ```
> >                 public void onEvent(GroupAtMessageEvent event) {  
> >                     System.out.println("1");
> >                     if (event.getD().getContent().contains("session test")) {
> >                         event.reply("1");
> >                     }
> >                 }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 收群@消息代码，理应收到任何消息都打印一条消息出来，但并没有出现
> 
> log.info("token连接信息: " + botContext.getCertificate().getAccessToken()); 麻烦试一下本条代码是否有正常的token输出,

下午4:53:49: 正在执行 ':Main.main()'…

> Task :compileJava
> Task :processResources NO-SOURCE
> Task :classes

> Task :Main.main()
16:53:51.032 [main] DEBUG i.n.u.i.l.InternalLoggerFactory - Using SLF4J as the default logging framework
16:53:51.037 [main] DEBUG i.n.u.c.GlobalEventExecutor - -Dio.netty.globalEventExecutor.quietPeriodSeconds: 1
16:53:51.053 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.initialSize: 1024
16:53:51.053 [main] DEBUG i.n.u.i.InternalThreadLocalMap - -Dio.netty.threadLocalMap.stringBuilder.maxSize: 4096
16:53:51.069 [main] DEBUG i.n.u.i.PlatformDependent0 - -Dio.netty.noUnsafe: false
16:53:51.069 [main] DEBUG i.n.u.i.PlatformDependent0 - Java version: 8
16:53:51.070 [main] DEBUG i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
16:53:51.070 [main] DEBUG i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
16:53:51.070 [main] DEBUG i.n.u.i.PlatformDependent0 - sun.misc.Unsafe.storeFence: available
16:53:51.071 [main] DEBUG i.n.u.i.PlatformDependent0 - java.nio.Buffer.address: available
16:53:51.071 [main] DEBUG i.n.u.i.PlatformDependent0 - direct buffer constructor: available
16:53:51.072 [main] DEBUG i.n.u.i.PlatformDependent0 - java.nio.Bits.unaligned: available, true
16:53:51.072 [main] DEBUG i.n.u.i.PlatformDependent0 - jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
16:53:51.072 [main] DEBUG i.n.u.i.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, {int,long}): available
16:53:51.072 [main] DEBUG i.n.u.i.PlatformDependent - sun.misc.Unsafe: available
16:53:51.073 [main] DEBUG i.n.u.i.PlatformDependent - -Dio.netty.tmpdir: C:\Users\ADMINI~1\AppData\Local\Temp (java.io.tmpdir)
16:53:51.073 [main] DEBUG i.n.u.i.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
16:53:51.073 [main] DEBUG i.n.u.i.PlatformDependent - Platform: Windows
16:53:51.074 [main] DEBUG i.n.u.i.PlatformDependent - -Dio.netty.maxDirectMemory: 3803185152 bytes
16:53:51.074 [main] DEBUG i.n.u.i.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
16:53:51.075 [main] DEBUG i.n.u.i.CleanerJava6 - java.nio.ByteBuffer.cleaner(): available
16:53:51.075 [main] DEBUG i.n.u.i.PlatformDependent - -Dio.netty.noPreferDirect: false
token连接信息: null

**Comment by KanyShigure** [comment]
16:57:22.490 [nioEventLoopGroup-2-1] ERROR c.b.o.w.h.ErrorCheckHandler - 检测到 Session 失效, 此时 token 是否已刷新 ? OpCode.INVALID_SESSION(code=9, name=Invalid Session, clientMethod=Receive, description=当 identify 或 resume 的时候，如果参数有错，服务端会返回该消息)
16:57:22.493 [nioEventLoopGroup-2-1] INFO  c.b.o.w.EventChannelHandler - WebSocket client closed with signal
16:57:25.413 [pool-1-thread-1] ERROR c.b.o.w.QQConnection - Exception occurred in wss connection
java.lang.IllegalArgumentException: [Assertion failed] - this argument is required; it must not be null
	at cn.hutool.core.lang.Assert.lambda$notNull$3(Assert.java:217)
	at cn.hutool.core.lang.Assert.notNull(Assert.java:197)
	at cn.hutool.core.lang.Assert.notNull(Assert.java:217)
	at cn.hutool.core.lang.Assert.notNull(Assert.java:233)
	at cn.byteforge.openqq.ws.WebSocketAPI.newShardSession(WebSocketAPI.java:68)
	at cn.byteforge.openqq.ws.WebSocketAPI.newStandaloneSession(WebSocketAPI.java:44)
	at org.example.Main.lambda$main$2(Main.java:45)
	at cn.byteforge.openqq.ws.BotContext.initSession(BotContext.java:129)
	at cn.byteforge.openqq.ws.QQConnection.lambda$doConnect$0(QQConnection.java:136)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

       (Main.java:45)
        QQConnection.connect(context, handlerSupplier,
                uuid -> WebSocketAPI.newStandaloneSession(Intent.register().withAll().done(), uuid, new HashMap<>(), context),
                uuid -> {
                    // TODO embed
                });

**Comment by mxlt02** [comment]
![image](https://github.com/user-attachments/assets/a82cc42c-c31f-4130-ae7d-88a8c593f4b8)
刚刚测试了 DEMO是正确的, 请检查腾讯机器人的配置

**Comment by KanyShigure** [comment]
> ![image](https://private-user-images.githubusercontent.com/57489136/348526482-a82cc42c-c31f-4130-ae7d-88a8c593f4b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5NDgzODAsIm5iZiI6MTcyMDk0ODA4MCwicGF0aCI6Ii81NzQ4OTEzNi8zNDg1MjY0ODItYTgyY2M0MmMtYzMxZi00MTMwLWFlN2QtODhhOGM1OTNmNGI4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDA5MDgwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThhMjg3YmUwOWFlMjc1ZWIzMzgwZDhiN2NjZjk3ZDRlZWI3NTU0OTc0MmEyOGFlOWZjNWNiYzAzZTg2NWNhZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DxM-f7b5WhFtNT81XXL20vDZsutvejU4uuL2XMQ1Cpo) 刚刚测试了 DEMO是正确的, 请检查腾讯机器人的配置

似乎是token有问题，一直为null，见上面报错，java.lang.IllegalArgumentException: [Assertion failed] - this argument is required; it must not be null，但方法实参没有null
机器人配置为 公域 沙箱 已配置好群已已加入 id和secret均为当场生成 还有其他的需要配置吗

**Comment by KanyShigure** [comment]
使用另一个SDK，能够正常连接和获得信息，https://github.com/Kloping/qqpd-bot-java ，   

> 但是这个SDK不支持群消息事件（bot连接成功，频道消息可以收到），可以参考一下是哪里出的问题

**修正，经测试，项目 qqpd-bot-java 的所有功能均为完好，包括群消息事件，能够正常使用任何功能，但依赖兼容性存在一些问题，相同的账号和参数在使用他的框架的情况下可以使用，使用你的则无法使用，故认为你的框架有问题，可以参考修复一下**

**Comment by byteforgecn** [comment]
是一个gson的依赖有兼容性问题吗

**Comment by KanyShigure** [comment]
> 是一个gson的依赖有兼容性问题吗

另一个 就是我回复的那个 不是现在贴issue的这个 这个还是用不了
